src/pages/ExplainPage.tsx

<br>
<br>
close #11 
<br>
<br>
- 설명페이지 퍼블리싱 <br>
- <br>
<br>

design: 설명페이지 퍼블리싱

---

public/css/reset.css
src/components/Navbar.tsx
src/pages/BlockPage.tsx
src/pages/BlockedURLPage.tsx
src/pages/ExplainPage.tsx
src/pages/FullPage.tsx
src/pages/MainPage.tsx
tailwind.config.js

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

Design: BlockedURLPage 생성

---

src/pages/BlockPage.tsx

<br>
<br>
close #13 
<br>
<br>
- 차단페이지 퍼블리싱 <br>
- <br>
<br>

design: 차단페이지 퍼블리싱

---

package-lock.json
package.json
src/pages/BlockPage.tsx

<br>
<br>
close #18 
<br>
<br>
- <br>
- <br>
<br>

feat: dayjs 라이브러리를 이용하여 오늘 날짜 보여주기

---

src/App.tsx
src/pages/AuthFailPage.tsx
src/pages/MemePage.tsx
src/pages/PhotoAuthPage.tsx

<br>
<br>
close #20 
<br>
<br>
- <br>
- <br>
<br>

design: 나머지 페이지 생성

---

src/pages/BlockedURLPage.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

design: 차단된 사이트 디자인

---

src/pages/BlockedURLPage.tsx
src/pages/FullPage.tsx

<br>
<br>
close #25 
<br>
<br>
- <br>
- <br>
<br>

design: BlockedURLPage 퍼블리싱 수정

---

src/components/Logo.tsx
src/pages/BlockedURLPage.tsx
src/pages/MemePage.tsx
src/pages/PhotoAuthPage.tsx

<br>
<br>
close #27 
<br>
<br>
- <br>
- <br>
<br>

design: FOCUS 로고 넣기

---

package-lock.json
package.json
src/api/api.ts
src/api/login.ts

<br>
<br>
close #41 
<br>
<br>
- <br>
- <br>
<br>

feat: api.ts

---

src/App.tsx
src/components/Drag.tsx
src/pages/DragPage.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

feat: 드래그로 움직이기

---

src/App.tsx
src/api/login.ts
src/api/signUp.ts
src/pages/LoginPage.tsx

<br>
<br>
close #45 
<br>
<br>
- <br>
- <br>
<br>

feat: 로그인 API 연동

---

src/App.tsx
src/api/login.ts
src/api/signUp.ts
src/main.tsx
src/pages/LoginPage.tsx
src/pages/SignUpPage.tsx

<br>
<br>
close #47 
<br>
<br>
- <br>
- <br>
<br>

feat: 회원가입 API 연동

---

src/api/mostBlocked.ts
src/pages/BlockPage.tsx

<br>
<br>
close #49 
<br>
<br>
- <br>
- <br>
<br>

feat: 최고 빈도 사이트 5개 API 연동

---

src/api/login.ts
src/api/uploadImage.ts
src/pages/PhotoAuthPage.tsx

<br>
<br>
close #51 
<br>
<br>
- <br>
- <br>
<br>

feat: 사진 제출 API 연동

---

src/api/stat.ts
src/pages/StatsPage.tsx

<br>
<br>
close #54 
<br>
<br>
- <br>
- <br>
<br>

feat: 통계 API 연동

---

package-lock.json
package.json
src/store/store.ts

<br>
<br>
close #56 
<br>
<br>
- <br>
- <br>
<br>

chore: Justand 설치

---

src/api/blockSites.ts
src/pages/BlockPage.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

feat/#52:차단단api추가

---

src/components/Navbar.tsx

<br>
<br>
close #68 
<br>
<br>
- <br>
- <br>
<br>

feat: useNavigate

---

src/api/unblock.ts
src/pages/UnblockPage.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

feat: 차단해제하기API연동

---

src/pages/LoginPage.tsx

<br>
<br>
close #80 
<br>
<br>
- <br>
- <br>
<br>

design: 로그인 페이지 퍼블리싱 수정

---

src/pages/AuthFailPage.tsx
src/pages/UnblockPage.tsx

<br>
<br>
close #83 
<br>
<br>
- <br>
- <br>
<br>

feat: 버튼 클릭 시 url 이동

---

src/pages/BlockPage.tsx

<br>
<br>
close #85 
<br>
<br>
- <br>
- <br>
<br>

feat: 파비콘 표시

---

src/pages/SignUpPage.tsx

<br>
<br>
close #91 
<br>
<br>
- <br>
- <br>
<br>

design: 회원가입 페이지 퍼블리싱 수정

---

src/pages/LoginPage.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

design:로그인페이지수정

---

src/pages/LoginPage.tsx
src/pages/SignUpPage.tsx

<br>
<br>
close #93 
<br>
<br>
- <br>
- <br>
<br>

design: 회원가입, 로그인 페이지 퍼블리싱 수정

---

package-lock.json
package.json
src/pages/StatsPage.tsx

<br>
<br>
close #95 
<br>
<br>
- <br>
- <br>
<br>

feat: chart.js로 통계 만들기

---

src/pages/AuthFailPage.css
src/pages/AuthFailPage.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

감옥떨어지는 거 구현 -> 추후 사람과 감옥 분리 필요

---

src/components/Navbar.tsx
src/pages/BlockPage.tsx
src/pages/ExplainPage.tsx
src/pages/FullPage.tsx
src/pages/MainPage.tsx
src/pages/StatsPage.tsx
src/pages/UnblockPage.tsx

<br>
메뉴 눌렀을때 이동하도록 수정
<br>
close #100 
<br>
<br>
- <br>
- <br>
<br>

메뉴 눌렀을때 이동하도록 수정

---

src/components/Navbar.tsx
src/pages/BlockPage.tsx
src/pages/ExplainPage.tsx
src/pages/FullPage.tsx
src/pages/MainPage.tsx

<br>
<br>
close #107 
<br>
<br>
- <br>
- <br>
<br>

feat: 메뉴 눌렀을때 이동하는 기능 수정

---

src/pages/UnblockPage.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

feat: 차단 해제 페이지 user_id 연동

---

src/index.css
src/pages/BlockPage.tsx

<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

feat:시간 스타일링

---

src/pages/LoginPage.tsx

<br>
<br>
close #119 
<br>
<br>
- <br>
- <br>
<br>

feat: 로그인 페이지에서 회원가입 페이지 이동

---

src/pages/PhotoAuthPage.tsx

<br>
기능 동작 제대로 돌아가는지 확인 완료
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>

기능 동작 제대로 돌아가는지 확인 완료

---

src/pages/PhotoAuthPage.tsx

<br>
<br>
close #124 
<br>
<br>
- <br>
- <br>
<br>

design: 사진 인증 페이지 디자인 수정

---

src/pages/BlockPage.tsx

<br>
<br>
close #126 
<br>
<br>
- <br>
- <br>
<br>

design: 최대 빈도 사이트 5개

---

src/api/taskId.ts
src/pages/PhotoAuthPage.tsx

<br>
<br>
close #131 
<br>
<br>
- <br>
- <br>
<br>

feat: task id API

---

src/index.css

<br>
<br>
close #133 
<br>
<br>
- <br>
- <br>
<br>

design: Made with fullPage.js 제거
